
### POST: Create a new location
POST http://localhost:3000/api/locations
Content-Type: application/json

{
  "latitude": 200,
  "longitude": -300
}

### GET: Retrieve all locations
GET http://localhost:3000/api/locations

### GET: Retrieve location with id of 1
GET http://localhost:3000/api/locations/7

### DELETE: Remove a specific location by ID
DELETE http://localhost:3000/api/locations/1