name: Merge to Main if Tests Pass

on:
  push:
    branches:
      - "feature/*"

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Merge branch into main if tests pass
      - name: Merge to main
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin main
          git checkout main
          git merge ${{ github.ref_name }} || echo "Merge conflict detected"
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-merged by GitHub Actions"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Delete feature branch after merge
      - name: Delete feature branch
        if: success()
        run: |
          branch_name="${{ github.ref_name }}"
          if [ "$branch_name" != "main" ]; then
            git push origin --delete "$branch_name" || echo "Branch deletion failed"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
